Version 0.1 - Unstable
the first upload! is able to boot but crashes soon after due to inheritance issues 
"  AttributeError: 'MuffinAI' object has no attribute 'units'  "